export const IMPORT_SETTINGS_REQUEST = 'IMPORT_SETTINGS_REQUEST'
export const IMPORT_SETTINGS_SUCCESS = 'IMPORT_SETTINGS_SUCCESS'
export const IMPORT_SETTINGS_FAILURE = 'IMPORT_SETTINGS_FAILURE'

export const EXPORT_SETTINGS_REQUEST = 'EXPORT_SETTINGS_REQUEST'
export const EXPORT_SETTINGS_SUCCESS = 'EXPORT_SETTINGS_SUCCESS'
export const EXPORT_SETTINGS_FAILURE = 'EXPORT_SETTINGS_FAILURE'
